---
abstract: 'A composable RESTful JSON API to DBIx::Class schemas using roles and Web::Machine'
author:
  - 'Tim Bunce <Tim.Bunce@pobox.com>'
build_requires:
  DBIx::Class::Fixtures: '1.001025'
  Data::Printer: '0'
  Module::Pluggable: '0'
  Sort::Key: '0'
  Test::Compile: v1.1.0
  Test::DBIx::Class: '0'
  Test::HTTP::Response: '0'
  Test::More: '0.98'
  Test::Most: '0'
  Test::Pod: '0'
  ToolSet: '0'
  autodie: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.022, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebAPI-DBIC
requires:
  Alien::Web::HalBrowser: '0'
  Carp: '0'
  DBIx::Class: '0.08250'
  Data::Dumper::Concise: '0'
  HTTP::Headers::ActionPack: '0'
  HTTP::Throwable: '0'
  JSON::MaybeXS: '0'
  List::Util: '0'
  Module::Runtime: '0'
  Moo: '1.001000'
  Path::Router: '0.13'
  Plack: '1.0033'
  Plack::App::File: '0'
  Plack::App::Path::Router: '0.06'
  SQL::Translator: '0.11018'
  Scalar::Util: '0'
  String::CamelCase: '0'
  Sub::Exporter: '0'
  Sub::Quote: '0'
  Try::Tiny: '0'
  URI: '0'
  Web::Machine: '0.15'
  namespace::clean: '0'
  parent: '0'
  perl: '5.010'
resources:
  IRC: irc://irc.perl.org/#webapi
  bugtracker: https://github.com/timbunce/WebAPI-DBIC/issues
  homepage: https://github.com/timbunce/WebAPI-DBIC
  repository: https://github.com/timbunce/WebAPI-DBIC.git
version: '0.002005'
